### ISSUE TITLE
Which tool could displays alignment or bed as narrow as possible? 

### ISSUE THREAD

**Issue by songxd17** [cmdcolin/awesome-genome-visualization#32]
Dear Author,
  Thanks for the amazing contribution. 
  I wonder if you could recommend any genome browser that could displays very thin and dense alignments or bed, just like supp fig 2B in this paper:
 https://static-content.springer.com/esm/art%3A10.1038%2Fnature12121/MediaObjects/41586_2013_BFnature12121_MOESM98_ESM.pdf
  the alignment displayed by IGV is too thick for me and the space between each reads seems to be not adjustable.
  
Thanks!

**Comment by cmdcolin** [comment]
that screenshot definitely looks like a igv svg export. I am not aware of a lot of features of igv about controlling height though!

**Comment by cmdcolin** [comment]
in alignments track there is the "compact" mode, not sure if normal bed tracks in IGV have that

**Comment by cmdcolin** [comment]
my bet is these are actually alignments tracks using the compact view in igv instead of bed, because there is the histogram count above them. just an idea. anyways, can maybe close for now

**Comment by cmdcolin** [comment]
nature always marks up figures to make em look fancier anyways :)
