### ISSUE TITLE
Something wrong with the colors

### ISSUE THREAD

**Issue by tuner** [cmdcolin/awesome-genome-visualization#52]
Hi Colin,
It seems that you have introduced a new dark theme 🌚

However, text is barely visible. (Tested on Mac with Chrome and Firefox)

![image](https://github.com/user-attachments/assets/c2ecb9ff-14ea-4dab-a545-f561067d98a0)

**Comment by cmdcolin** [comment]
alrighty, i redeployed a fix that should respect the computers prefers-light/dark theme better!

**Comment by tuner** [comment]
Thanks. Looks good!
