### ISSUE TITLE
enrichplot

### ISSUE THREAD

**Issue by sk-sahu** [cmdcolin/awesome-genome-visualization#6]
Do you think enrichplot can be part of any category? This has a diverse set of plots for geneset enrichment visualization.

enrichoplot Bioconductor package link: https://www.bioconductor.org/packages/release/bioc/html/enrichplot.html

Some examples can be found here - https://yulab-smu.github.io/clusterProfiler-book/chapter12.html

**Comment by cmdcolin** [comment]
My main interest is in "genome browser" or "genome coordinate" based visualizations, however I have made some exceptions!  See the heatmap category. Would be happy to add those that are of interest
